TABLICA1	DS		5*INTEGER
ZMIENNA1	DS		INTEGER
ZMIENNA2	DS		INTEGER
TABLICA2	DS		5*INTEGER
CZT			DC		INTEGER(4)
DWN			DC		INTEGER(12)
ZERO		DC		INTEGER(0)
			READ	TABLICA1(5)
			READ	ZMIENNA1
			READ	ZMIENNA2
			READ	TABLICA2(5)		
			L		0, DWN
SPOSOB1		L		1, 20
SPOSOB2		L		2, ZMIENNA2
SPOSOB3		L		3, TABLICA1(0)
SPOSOB4		L		4, 28(0)