ROZM		DC		INTEGER(10)
CZT			DC		INTEGER(4)
JEDEN		DC		INTEGER(1)
ZERO		DC		INTEGER(0)
WEKTOR		DC		10*INTEGER()
OSTATNI		DC		INTEGER(9)
			READ	WEKTOR(10)
			LA		1, WEKTOR
			L		2, JEDEN
			L 		4, 0(1)
PETLA		C		2, OSTATNI
			JZ		KONIEC_P
			LR		3, 1
			L		6, 0(1)
			A		3, CZT
			L		5, 0(3)
			CR		4, 6
			JZ		NIE_USUWAJ
			JN		NIE_USUWAJ
			CR		6, 5
			JZ		NIE_USUWAJ
			JN		NIE_USUWAJ
KOPIA		LR		4, 6
USUWAM		L		3, ZERO
			ST		3, 0(1)
NIE_USUWAJ	LR		4, 6
			A		1, CZT
			A		2, JEDEN
			J		PETLA
KONIEC_P	WRITE	WEKTOR(10)
