ROZM	DC		INTEGER(10)
JEDEN	DC		INTEGER(1)
ZERO	DC		INTEGER(0)
CZT		DC		INTEGER(4)
WEKTOR	DC		10*INTEGER
SUMA	DS		INTEGER
		READ	WEKTOR(10)
		LA		1, WEKTOR
		L		3, ZERO
		L		4, ZERO
PETLA	C		3, ROZM
		JZ		KONIEC
		L		2, 0(1)
		AR		4, 2
		A		1, CZT
		A		3, JEDEN
		J		PETLA
KONIEC	ST		4, SUMA